package org.ssh.demo.pojo;
// Generated 2020-5-28 17:26:24 by Hibernate Tools 3.2.2.GA



/**
 * OrderInfo generated by hbm2java
 */
public class OrderInfo  implements java.io.Serializable {


     private Long id;
     private String orderName;
     private String orderAddress;

    public OrderInfo() {
    }

    public OrderInfo(String orderName, String orderAddress) {
       this.orderName = orderName;
       this.orderAddress = orderAddress;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getOrderName() {
        return this.orderName;
    }
    
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }
    public String getOrderAddress() {
        return this.orderAddress;
    }
    
    public void setOrderAddress(String orderAddress) {
        this.orderAddress = orderAddress;
    }




}


