package org.ssh.demo.pojo;
// Generated 2020-5-28 9:14:53 by Hibernate Tools 3.2.2.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private String fundId;
     private String userName;
     private Byte userSex;
     private String userAddress;
     private String month;

    public User() {
    }

    public User(String fundId, String userName, Byte userSex, String userAddress, String month) {
       this.fundId = fundId;
       this.userName = userName;
       this.userSex = userSex;
       this.userAddress = userAddress;
       this.month = month;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getFundId() {
        return this.fundId;
    }
    
    public void setFundId(String fundId) {
        this.fundId = fundId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Byte getUserSex() {
        return this.userSex;
    }
    
    public void setUserSex(Byte userSex) {
        this.userSex = userSex;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getMonth() {
        return this.month;
    }
    
    public void setMonth(String month) {
        this.month = month;
    }




}


